name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '4.8.x'

    - name: Restore dependencies
      run: dotnet restore CyberSecurityBot.sln

    - name: Build solution
      run: dotnet build CyberSecurityBot.sln --no-restore --configuration Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CybersecurityBot-Build
        path: ./CyberSecurityBot/bin/Release/
